CREATE DATABASE bot_timetable;
\c bot_timetable
CREATE ROLE bot_user NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE USER bot_tg WITH PASSWORD '<pw>';
GRANT bot_user TO bot_tg;
GRANT CONNECT ON DATABASE bot_timetable to bot_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO bot_user;

CREATE ROLE bot_admin NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION;
CREATE USER admin_tt WITH PASSWORD '<pw>';
GRANT bot_admin to admin_tt;
GRANT ALL PRIVILEGES ON DATABASE bot_timetable TO bot_admin;
